---
language: cpp
os: linux
env: ARCH=x86_64
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.3-xenial
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install libgl1-mesa-dev
  - sudo apt-get -y install qt512base
  - sudo apt-get -y install qt512quickcontrols
  - sudo apt-get -y install qt512quickcontrols2

script:
  - source /opt/qt512/bin/qt512-env.sh
  - mkdir build
  - cd build
  - /opt/qt512/bin/qmake ../qt-linguist-to-csv.pro
  - make -j$(nproc)
